name: CI Workflow  # The name of the workflow.

on:
  push:
    branches:
      - main  # Fixed missing space between - and branch name
  pull_request:
    branches:
      - main  # Fixed missing space between - and branch name

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Changes Start Here
      - name: Run Tests  # Fixed missing space after - and name
        run: poetry run invoke test

      - name: Run Linting  # Fixed missing space after - and name
        run: poetry run invoke lint

      - name: Run Typing Checks  # Fixed missing space after - and name
        run: poetry run invoke type
